### PR TITLE
Update German translation to match latest app version

### PR DESCRIPTION
**Pull request by bttrx**

### CODE REVIEW

**Comment by albertvaka** [comment]
This might not fit in all screens, though. Maybe `n.v.` without the space is better? The space is a bit tight in this dialog.

**Comment by bttrx** [comment]
`n.v.` (w/o the space) is wrong in German, same as `z.B.` (English: `e.g.`) or `d.h.` (English: `i.e.`) are.
The rule for German language is clear on that: "Never w/o the space".
If dialog space is a problem, why not use an "&ndash;" (ndash) instead?

**Comment by albertvaka** [comment]
I've done some testing on a Pixel 4a (a device with a small screen but still quite common): "n. v." doesn't fit but neither does "N/A". I thought the dash would be a good idea but I think it looks a bit weird after the minus button. 

image

image

**Comment by albertvaka** [comment]
I think I'll go with the empty set symbol. It also has the advantage that it doesn't need translation, so we will avoid having this problem with each language.

image

**Comment by bttrx** [comment]
> I think I'll go with the empty set symbol. It also has the advantage that it doesn't need translation, so we will avoid having this problem with each language.

Ok, but I see a problem with your solution:

1. **Who** really knows the empty set symbol? (I didn't.)
2. I already use `Ø` in "stats_averages" as a German "translation" of "Avg.", because I didn't find a good abbrev for "Durchschnitt".

Proposal: Can't we just use "0" (zero) to represent no goal? (Because counters only count upwards in your app.)

**Comment by albertvaka** [comment]
I think goal = 0 and no goal are different things, so I would prefer something other than a number. But if Ø is used for average then we should use some other symbol.

**Comment by bttrx** [comment]
> I think goal = 0 and no goal are different things [...]

Not for me. How would a goal of 0 make sense to you otherwise?

**Comment by albertvaka** [comment]
Well, in the app it has a different meaning when your select 0, doesn't it? Otherwise when selecting 0 it would show the "goal met" checkmark all the time if 0 is selected.

**Comment by bttrx** [comment]
I guess, we still have a different understanding about goals, which makes it hard to find a proper solution. By the way: I don't use goals at all.

> Well, in the app it has a different meaning when your select 0, doesn't it?

How? You can't select 0 in your app.

> Otherwise when selecting 0 it would show the "goal met" checkmark all the time if 0 is selected.

I see no problem in adding some "intelligence" to the app, e.g., "if goal = 0 then don't show checkmark" and "if goal = 0 then don't show '/0')".

**Comment by albertvaka** [comment]
I opted for using the full "Durchschnitt" for "average" and keeping the Ø symbol for no goal. I'm going to make a new release now.

**Comment by bttrx** [comment]
That's a decision.

**Pull request closed without merging**
